#!/bin/bash

# Compile u-boot for a bunch of ARM boards we want and
# keep detailed records of where the code came from.

TARGET_ARCH=$1

if [ ! -n "$TARGET_ARCH" ]; then
	echo "Usage: $0 <arch> [board]"
	exit 1
fi

### Locate acceptible cross-compiler toolchain
TOOLCHAIN_ARCH=$TARGET_ARCH
CROSS_TOOL_PREFIX=""
# Alias arm64 == aarch64
if [ "$TARGET_ARCH" == "arm64" ]; then
	TOOLCHAIN_ARCH=aarch64
fi
if [ $(uname -m) == $TOOLCHAIN_ARCH ]; then
	echo "Native architecture build"
	CROSS_TOOL_PREFIX=""
	if ! [ -x "$(command -v ld)" ]; then
		echo "Error: development tools not installed!"
		exit 1
	fi
else
	echo "Cross compile build"
	for i in unknown-haiku none-eabi linux-gnu elf; do
		if [ -x "$(command -v $TOOLCHAIN_ARCH-$i-ld)" ]; then
			echo "Found $i cross compiler!"
			CROSS_TOOL_PREFIX=$TOOLCHAIN_ARCH-$i-
			break;
		fi
	done
	if ! [ -n "$CROSS_TOOL_PREFIX" ]; then
		echo "Error: Unable to locate compatible cross-compiler in PATH!"
		exit 1
	fi
fi


if ! [ -d "$TARGET_ARCH" ]; then
	echo "Error: Unable to locate ./$TARGET_ARCH directory!"
	exit 1
fi
echo "Beginning $TARGET_ARCH build..."

TMP="/tmp/$TARGET_ARCH-build"
GIT_REPO="git://git.denx.de/u-boot.git"

echo "Cloning sources..."
git clone $GIT_REPO $TMP
GIT_DATE=$(git -C $TMP log -1 --format=%cd)
GIT_HASH=$(git -C $TMP log -1 --format=%H)

WORK_QUEUE=$(find $TARGET_ARCH/ -mindepth 1 -type d)
if [ $# -eq 2 ]; then
	WORK_QUEUE="$TARGET_ARCH/$2"
fi

for dir in $WORK_QUEUE; do
	BUILD_CONFIG="$dir/.build"
	if [ ! -f $BUILD_CONFIG ]; then
		echo "Skipping $dir due to lack of build manifest"
		continue;
	fi

	# This could be better, but it gets the job done.
	CONFIG=$(grep "config=" $BUILD_CONFIG | cut -d "=" -f2)
	NAME=$(grep "name=" $BUILD_CONFIG | cut -d "=" -f2)
	URL=$(grep "url=" $BUILD_CONFIG | cut -d "=" -f2)
	ARTIFACTS=$(grep "artifacts=" $BUILD_CONFIG | cut -d "=" -f2)
	EXTRA=$(grep "extra=" $BUILD_CONFIG | cut -d "=" -f2)

	echo "Building $NAME..."

	make -C $TMP clean
	make -C $TMP $CONFIG
	if [ $? -ne 0 ]; then
		echo "Error configuring $dir"
		continue;
	fi
	ARCH=$TARGET_ARCH CROSS_COMPILE=$CROSS_TOOL_PREFIX make -C $TMP -j2
	if [ $? -ne 0 ]; then
		echo "Error building $dir"
		continue;
	fi

	echo "Collecting artifacts..."
	FILES=""
	for x in $ARTIFACTS; do
		echo "Searching for $x..."
		find $TMP -name "$x" -exec cp -f {} $dir/ \;
		FILES="$FILES $x"
	done

	# Populate README.md
	cp tools/README.template $dir/README.md
	sed -i "s^%%URL%%^$URL^g" $dir/README.md
	sed -i "s^%%DATE%%^$(date)^g" $dir/README.md
	sed -i "s^%%GIT_REPO%%^$GIT_REPO^g" $dir/README.md
	sed -i "s^%%GIT_DATE%%^$GIT_DATE^g" $dir/README.md
	sed -i "s^%%GIT_HASH%%^$GIT_HASH^g" $dir/README.md
	sed -i "s^%%BOARD%%^$NAME^g" $dir/README.md
	sed -i "s^%%FILES%%^$FILES^g" $dir/README.md
	sed -i "s^%%CONFIG%%^$CONFIG^g" $dir/README.md
	sed -i "s^%%TARGET_ARCH%%^$TARGET_ARCH^g" $dir/README.md
	sed -i "s^%%CROSS_TOOL%%^$CROSS_TOOL_PREFIX-^g" $dir/README.md
done
