#!/bin/bash

if [[ $# -ne 2 ]]; then
	echo "usage: $0 <OpenSBI Version> <platform>"
	exit 1
fi

BASE=/tmp/opensbi
VERSION=$1
PLATFORM=$2

wget https://github.com/riscv-software-src/opensbi/releases/download/v${VERSION}/opensbi-${VERSION}-rv-bin.tar.xz -O ${BASE}/sbi.tar.xz >${BASE}/opensbi_obtain.log 2>&1

mkdir -p /tmp/opensbi/v${VERSION}/riscv64/${PLATFORM}
cd ${BASE}/v${VERSION}/riscv64/${PLATFORM}
tar xf ${BASE}/sbi.tar.xz --transform='s,.*/,,' opensbi-${VERSION}-rv-bin/share/opensbi/lp64/${PLATFORM}/firmware/fw_dynamic.bin
rm ${BASE}/sbi.tar.xz
echo ${BASE}/v${VERSION}/riscv64/${PLATFORM}/fw_dynamic.bin
